// Grind 75 (default 8-week schedule) from techinterviewhandbook.org/grind75.
// Solved on LeetCode; the site only tracks what you mark done.
const WEEKS = [
  [
    'two-sum|Two Sum|Easy|15',
    'valid-parentheses|Valid Parentheses|Easy|20',
    'merge-two-sorted-lists|Merge Two Sorted Lists|Easy|20',
    'best-time-to-buy-and-sell-stock|Best Time to Buy and Sell Stock|Easy|20',
    'valid-palindrome|Valid Palindrome|Easy|15',
    'invert-binary-tree|Invert Binary Tree|Easy|15',
    'valid-anagram|Valid Anagram|Easy|15',
    'binary-search|Binary Search|Easy|15',
    'flood-fill|Flood Fill|Easy|20',
    'lowest-common-ancestor-of-a-binary-search-tree|Lowest Common Ancestor of a Binary Search Tree|Easy|20',
    'balanced-binary-tree|Balanced Binary Tree|Easy|15',
    'linked-list-cycle|Linked List Cycle|Easy|20',
    'implement-queue-using-stacks|Implement Queue using Stacks|Easy|20',
  ],
  [
    'first-bad-version|First Bad Version|Easy|20',
    'ransom-note|Ransom Note|Easy|15',
    'climbing-stairs|Climbing Stairs|Easy|20',
    'longest-palindrome|Longest Palindrome|Easy|20',
    'reverse-linked-list|Reverse Linked List|Easy|20',
    'majority-element|Majority Element|Easy|20',
    'add-binary|Add Binary|Easy|15',
    'diameter-of-binary-tree|Diameter of Binary Tree|Easy|30',
    'middle-of-the-linked-list|Middle of the Linked List|Easy|20',
    'maximum-depth-of-binary-tree|Maximum Depth of Binary Tree|Easy|15',
    'contains-duplicate|Contains Duplicate|Easy|15',
    'maximum-subarray|Maximum Subarray|Medium|20',
  ],
  [
    'insert-interval|Insert Interval|Medium|25',
    '01-matrix|01 Matrix|Medium|30',
    'k-closest-points-to-origin|K Closest Points to Origin|Medium|30',
    'longest-substring-without-repeating-characters|Longest Substring Without Repeating Characters|Medium|30',
    '3sum|3Sum|Medium|30',
    'binary-tree-level-order-traversal|Binary Tree Level Order Traversal|Medium|20',
    'clone-graph|Clone Graph|Medium|25',
    'evaluate-reverse-polish-notation|Evaluate Reverse Polish Notation|Medium|30',
  ],
  [
    'course-schedule|Course Schedule|Medium|30',
    'implement-trie-prefix-tree|Implement Trie (Prefix Tree)|Medium|35',
    'coin-change|Coin Change|Medium|25',
    'product-of-array-except-self|Product of Array Except Self|Medium|30',
    'min-stack|Min Stack|Medium|20',
    'validate-binary-search-tree|Validate Binary Search Tree|Medium|20',
    'number-of-islands|Number of Islands|Medium|25',
    'rotting-oranges|Rotting Oranges|Medium|30',
  ],
  [
    'search-in-rotated-sorted-array|Search in Rotated Sorted Array|Medium|30',
    'combination-sum|Combination Sum|Medium|30',
    'permutations|Permutations|Medium|30',
    'merge-intervals|Merge Intervals|Medium|30',
    'lowest-common-ancestor-of-a-binary-tree|Lowest Common Ancestor of a Binary Tree|Medium|25',
    'time-based-key-value-store|Time Based Key-Value Store|Medium|35',
    'accounts-merge|Accounts Merge|Medium|30',
    'sort-colors|Sort Colors|Medium|25',
  ],
  [
    'word-break|Word Break|Medium|30',
    'partition-equal-subset-sum|Partition Equal Subset Sum|Medium|30',
    'string-to-integer-atoi|String to Integer (atoi)|Medium|25',
    'spiral-matrix|Spiral Matrix|Medium|25',
    'subsets|Subsets|Medium|30',
    'binary-tree-right-side-view|Binary Tree Right Side View|Medium|20',
    'longest-palindromic-substring|Longest Palindromic Substring|Medium|25',
    'unique-paths|Unique Paths|Medium|20',
    'construct-binary-tree-from-preorder-and-inorder-traversal|Construct Binary Tree from Preorder and Inorder Traversal|Medium|25',
  ],
  [
    'container-with-most-water|Container With Most Water|Medium|35',
    'letter-combinations-of-a-phone-number|Letter Combinations of a Phone Number|Medium|30',
    'word-search|Word Search|Medium|30',
    'find-all-anagrams-in-a-string|Find All Anagrams in a String|Medium|30',
    'minimum-height-trees|Minimum Height Trees|Medium|30',
    'task-scheduler|Task Scheduler|Medium|35',
    'lru-cache|LRU Cache|Medium|30',
  ],
  [
    'kth-smallest-element-in-a-bst|Kth Smallest Element in a BST|Medium|25',
    'minimum-window-substring|Minimum Window Substring|Hard|30',
    'serialize-and-deserialize-binary-tree|Serialize and Deserialize Binary Tree|Hard|40',
    'trapping-rain-water|Trapping Rain Water|Hard|35',
    'find-median-from-data-stream|Find Median from Data Stream|Hard|30',
    'word-ladder|Word Ladder|Hard|45',
    'basic-calculator|Basic Calculator|Hard|40',
    'maximum-profit-in-job-scheduling|Maximum Profit in Job Scheduling|Hard|45',
    'merge-k-sorted-lists|Merge k Sorted Lists|Hard|30',
    'largest-rectangle-in-histogram|Largest Rectangle in Histogram|Hard|35',
  ],
];

export const GRIND75 = WEEKS.flatMap((rows, w) => rows.map(r => {
  const [slug, title, difficulty, minutes] = r.split('|');
  return { id: 'g75-' + slug, track: 'grind75', week: w + 1, title, difficulty, minutes: +minutes, url: `https://leetcode.com/problems/${slug}/` };
}));
